// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvQisESARpF5wAhtVDFfslkdywvLewmAc',
    appId: '1:996068844165:web:54f43284420655bd9a7fec',
    messagingSenderId: '996068844165',
    projectId: 'diary-plus-app',
    authDomain: 'diary-plus-app.firebaseapp.com',
    storageBucket: 'diary-plus-app.appspot.com',
    measurementId: 'G-MWCJJPGN9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq_xZBHLjlBPE_hbUmrieBfZat8lpUrOU',
    appId: '1:996068844165:android:c1d273af3f8ef1409a7fec',
    messagingSenderId: '996068844165',
    projectId: 'diary-plus-app',
    storageBucket: 'diary-plus-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOBOsJrOwPPcpfiTTX-F2ZnLGIUIfYHcE',
    appId: '1:996068844165:ios:7f9bf296076fb6de9a7fec',
    messagingSenderId: '996068844165',
    projectId: 'diary-plus-app',
    storageBucket: 'diary-plus-app.appspot.com',
    iosBundleId: 'com.example.diaryPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOBOsJrOwPPcpfiTTX-F2ZnLGIUIfYHcE',
    appId: '1:996068844165:ios:f53cee96658115ff9a7fec',
    messagingSenderId: '996068844165',
    projectId: 'diary-plus-app',
    storageBucket: 'diary-plus-app.appspot.com',
    iosBundleId: 'com.example.diaryPlus.RunnerTests',
  );
}
